services:
  - type: web
    name: sons-of-garitos-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8108913508:AAHW3z0ujxvA3L4oeE1wuy4UZ4wnBoxrZ60"
